### PR TITLE
Add Files for Pkg3

### PR DESCRIPTION
**Pull request by jd-lara**
This PR adds files and dependencies to avoid package manager complaints and warnings. Most importantly, adds MOI as a dependency.

### CODE REVIEW

**Comment by joaquimg** [comment]
Thanks!
One question though, why JuMP doesn't need project.toml and manifest.toml?

**Comment by joaquimg** [comment]
Also, I am no proficient in Pkg3, this structure is leaving GLPK only needed for tests?

**Comment by jd-lara** [comment]
1. JuMP still relies mostly on REQUIRE to address package dependencies, using TOML is not mandatory yet but avoids the package manager having to parse the REQUIRE with Compat. 

Also, for the new registration, TOMLs will be mandatory. If you prefer we can avoid them for now since I also update the REQUIRE to include MathOptInterface. 

2. I noticed there is a REQUIRE in the test folder to use GLPK and run tests, but I didn't check if it is actually used in the testing code. That syntax to avoid making the package dependent on GLPK.

**Comment by joaquimg** [comment]
fair enough. project toml makes sense to me. but why the project has specific versions os packages? or they are minimums?

**Comment by jd-lara** [comment]
The specific versions of the dependencies are kept in the Manifest. The minimum version are set in the field compat at the Project.TOML but I didn't set them for ParameterJuMP

Here are the details of the TOML files format for packages https://julialang.github.io/Pkg.jl/dev/toml-files/ I think this a better explanation than mine

**Comment by joaquimg** [comment]
Thanks!
For now we probably dont need it.

**Pull request merged**
