### PR TITLE
[deprecation] Remove add_parameter in favor of variable macro

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by joaquimg** [comment]
Benchmarks?

**Comment by odow** [comment]
There are a few extra checks, but they're pretty minor:
```Julia
julia> @macroexpand @variable(model, p == 1, Param())
quote
    #= REPL[18]:1 =#
    JuMP._valid_model(model, :model)
    begin
        #= /Users/oscar/.julia/packages/JuMP/y5vgk/src/macros.jl:92 =#
        JuMP._error_if_cannot_register(model, :p)
        #= /Users/oscar/.julia/packages/JuMP/y5vgk/src/macros.jl:96 =#
        var"#9###290" = JuMP.add_variable(model, JuMP.build_variable(JuMP.var"#_error#90"{LineNumberNode,Tuple{Symbol,Expr,Expr}}(:(#= REPL[18]:1 =#), (:model, :(p == 1), :(Param()))), JuMP.VariableInfo(false, NaN, false, NaN, true, 1, false, NaN, false, false), Param()), "p")
        #= /Users/oscar/.julia/packages/JuMP/y5vgk/src/macros.jl:97 =#
        model[:p] = var"#9###290"
        #= /Users/oscar/.julia/packages/JuMP/y5vgk/src/macros.jl:102 =#
        p = var"#9###290"
    end
end
```
Its checking the model is valid, that `p` hasn't been used in the model already, storing `:p`, and setting the name. This will be imperceptible in any real workflow.

**Comment by jd-lara** [comment]
@odow look like this implementation now forces naming the parameter in the @variable() call. Before it was possible to have an "anonymous" parameter.

**Comment by odow** [comment]
See https://github.com/JuliaStochOpt/ParameterJuMP.jl#welcome-to-parameterjump
```Julia
anon = @variable(model, variable_type = Param())
```

**Comment by jd-lara** [comment]
> See https://github.com/JuliaStochOpt/ParameterJuMP.jl#welcome-to-parameterjump
> 
> ```julia
> anon = @variable(model, variable_type = Param())
> ```

Yeah, sorry I saw it afterwards.

**Pull request merged**
