### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by jd-lara**
Updates MOI, MA and JuMP depedencies.

### CODE REVIEW

**Comment by jd-lara** [comment]
@odow this seems ready for review

**Review by odow — APPROVED** [review]

**Comment by odow** [comment]
So just the MA change?

**Comment by jd-lara** [comment]
So far yeah, all of our tests are passing so I don't have anything else that might require changes

**Comment by jd-lara** [comment]
@odow I ran all the testing we can do over the weekend. This should be merged and tagged as soon as you can please.

**Pull request merged**
